# Generated by Django 4.2 on 2023-07-10 11:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان برند")),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.FileManager.upload_to, verbose_name="لوگو"
                    ),
                ),
                ("slug", models.SlugField(max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/غیرفعال"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام ویژگی")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/غیرفعال"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="FeatureDigitalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=60, verbose_name="مقدار")),
            ],
            options={
                "verbose_name": "مقدار دیجیتال ویژگی",
                "verbose_name_plural": "مقادیر دیجیتال ویژگی",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام کالا")),
                (
                    "short_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="خلاصه توضیحات کالا"
                    ),
                ),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات کالا"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="بهای کالا"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to=utils.FileManager.upload_to, verbose_name="تصویر اصلی"
                    ),
                ),
                ("slug", models.SlugField(max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/غیرفعال"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.brand",
                        verbose_name="برند کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالا",
                "verbose_name_plural": "کالاها",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to=utils.FileManager.upload_to, verbose_name="تصویر"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر کالا",
                "verbose_name_plural": "تصاویر کالا",
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analogue_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مقدار آنالوگ",
                    ),
                ),
                (
                    "digital_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_features",
                        to="products.featuredigitalvalue",
                        verbose_name="مقدار دیجیتال",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_features",
                        to="products.feature",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_features",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی کالا",
                "verbose_name_plural": "ویژگی\u200cهای کالا",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="عنوان دسته\u200cی کالا"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.FileManager.upload_to,
                        verbose_name="تصویر اصلی دسته",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات دسته"
                    ),
                ),
                ("slug", models.SlugField(max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/غیرفعال"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "subset_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsets",
                        to="products.productcategory",
                        verbose_name="زیرمجموعه\u200cی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cی کالا",
                "verbose_name_plural": "دسته\u200cهای کالا",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_products",
                to="products.productcategory",
                verbose_name="دسته\u200cی کالا",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductFeature",
                to="products.feature",
                verbose_name="ویژگی\u200cهای کالا",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="products.productcategory",
                verbose_name="دسته\u200cی کالا",
            ),
        ),
    ]
