# Generated by Django 4.2 on 2023-07-11 23:26

from django.db import migrations, models
import utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_brand_logo_alter_product_main_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=150, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر اصلی دسته"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(max_length=150, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="images",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر"
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
