# Generated by Django 4.2 on 2023-07-11 23:33

from django.db import migrations, models
import utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product_brand_alter_product_main_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="category",
        ),
        migrations.AddField(
            model_name="feature",
            name="categories",
            field=models.ManyToManyField(
                related_name="features",
                to="products.productcategory",
                verbose_name="دسته\u200cی کالا",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر اصلی دسته"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="images",
            field=models.ImageField(
                upload_to=utils.FileManager.upload_to, verbose_name="تصویر"
            ),
        ),
    ]
