# Generated by Django 4.2 on 2023-07-27 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "products",
            "0009_alter_product_main_image_alter_productcategory_image_and_more",
        ),
        ("accounts", "0005_alter_customer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ ثبت سفارش",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین ویرایش"
                    ),
                ),
                (
                    "is_finally",
                    models.BooleanField(default=False, verbose_name="نهایی شده"),
                ),
                (
                    "order_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کد سفارش",
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="درصد تخفیف روی سفارش"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=60, verbose_name="وضعیت سفارش")),
            ],
            options={
                "verbose_name": "وضعیت سفارش",
                "verbose_name_plural": "انواع وضعیت\u200cهای سفارش",
            },
        ),
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(max_length=60, verbose_name="نوع پرداخت"),
                ),
            ],
            options={
                "verbose_name": "روش پرداخت",
                "verbose_name_plural": "انواع روش\u200cهای پرداخت",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=1, verbose_name="تعداد")),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="قیمت کالا در فاکتور"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
        ),
    ]
