# Generated by Django 4.2 on 2023-07-29 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_order_status_alter_order_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="درصد تخفیف روی سفارش",
            ),
        ),
    ]
