# Generated by Django 4.2 on 2023-07-05 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="وضعیت ادمینی"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل وارد شده معتبر نیست", regex="^09\\d{9}"
                    )
                ],
                verbose_name="شماره موبایل",
            ),
        ),
    ]
