# Generated by Django 4.2 on 2023-07-10 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_is_staff_alter_customuser_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل وارد شده معتبر نیست.", regex="^09\\d{9}"
                    )
                ],
                verbose_name="شماره موبایل",
            ),
        ),
    ]
