# Generated by Django 4.2 on 2023-07-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_mobile_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="تلفن ثابت"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.FileManager.upload_to,
                        verbose_name="تصویر پروفایل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
            },
        ),
    ]
