# Generated by Django 4.2 on 2023-07-29 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0005_remove_order_discount_order_discount_percent"),
        ("accounts", "0009_alter_customer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی پرداخت"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                ("description", models.TextField(verbose_name="توضیحات پرداخت")),
                (
                    "is_finally",
                    models.BooleanField(
                        default=False, verbose_name="وضعیت نهایی/غیرنهایی"
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="کد وضعیت درگاه"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="شماره پیگیری پرداخت",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_payments",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
            },
        ),
    ]
