# Generated by Django 4.2 on 2023-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="discount_code",
            field=models.CharField(max_length=10, unique=True, verbose_name="کد تخفیف"),
        ),
    ]
