# Generated by Django 4.2 on 2023-08-03 11:35

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title1",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="متن اول"
                    ),
                ),
                (
                    "title2",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="متن دوم"
                    ),
                ),
                (
                    "title3",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="متن سوم"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.FileManager.upload_to,
                        verbose_name="تصویر اسلاید",
                    ),
                ),
                (
                    "slider_link",
                    models.URLField(blank=True, null=True, verbose_name="لینک اسلاید"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="فعال/غیرفعال"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدها",
            },
        ),
    ]
