# Generated by Django 4.2 on 2023-08-01 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "products",
            "0017_alter_product_main_image_alter_productcategory_image_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="نوع تراکنش")),
            ],
            options={
                "verbose_name": "نوع تراکنش",
                "verbose_name_plural": "انواع تراکنش",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(verbose_name="تعداد")),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="قیمت واحد"
                    ),
                ),
                (
                    "register_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="warehouses.transactiontype",
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "user_registered",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
    ]
